version: '3.4'

services:

#  app:
#    build: .
#    ports:
#      - "8081:8080"
#    depends_on:
#      - postgres
#      - localstack
#    networks:
#      - booksalesonline-network

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - AWS_DEFAULT_REGION=sa-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/aws_s3_create_bucket.sh:/docker-entrypoint-initaws.d/create_bucket.sh

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=#P0stgr3sP@ss
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      # copy the sql script to create tables
      - ./localstack/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - booksalesonline-network

#  pgadmin:
#    image: dpage/pgadmin4:6.20
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "renanvianamarcelino@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadmin-pass"
#    ports:
#      - "16543:80"
#    depends_on:
#      - postgres
#    networks:
#      - booksalesonline-network

networks:
  booksalesonline-network:
    driver: bridge