package com.renan.booksalesonline.application.mediators;

public enum UseCaseType {
    UNKNOWN,
    COUNTRY_GET_ALL, COUNTRY_GET_BY_ID, COUNTRY_CREATE, COUNTRY_UPDATE, COUNTRY_REMOVE,
    AUTHOR_GET_ALL, AUTHOR_GET_BY_ID, AUTHOR_CREATE, AUTHOR_UPDATE, AUTHOR_REMOVE,
}
